# Generated by Django 5.1.2 on 2024-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='kpi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='admin',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='liga',
            field=models.CharField(choices=[('Hacker', 'Hacker'), ('Coder', 'Coder'), ('Gamer', 'Gamer')], default='Gamer', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rating_number',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
