# Generated by Django 5.1.2 on 2024-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_admin_kpi_alter_admin_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="payment_summa",
        ),
        migrations.AddField(
            model_name="group",
            name="payment_summa",
            field=models.DecimalField(
                decimal_places=2, default=1090000.0, max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="liga",
            field=models.CharField(
                choices=[("Hacker", "Hacker"), ("Coder", "Coder"), ("Gamer", "Gamer")],
                default="Coder",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
